
name: Github action for your deployment

on:
    push:
      branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: 11
            distribution: 'temurin'
            cache: maven
        - name: install with Maven
          run: |
            mvn clean install
            mvn -f pom.xml clean package

        - name: Create a Dockerfile
          run: |
            echo "
             FROM openjdk:11
             ADD target/springmaven-0.0.1-SNAPSHOT.jar springmaven-0.0.1-SNAPSHOT.jar
             ENTRYPOINT ["java","-jar","./springmaven-0.0.1-SNAPSHOT.jar"]
             " > Dockerfile

        - name: Docker login
          uses: docker/login-action@v1 
          with:
            registry: registry.patr.cloud
            username: ashish-oli
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Build image from Dockerfile and push to patr-registry
          run: |
            docker build . -t ashish-oli/deployment
            docker tag ashish-oli/deployment registry.patr.cloud/personal-workspace-1424404d9fff474bba7f23825681f6a8/maven:latest 
            docker push registry.patr.cloud/personal-workspace-1424404d9fff474bba7f23825681f6a8/maven:latest 
