
name: Github action for your deployment

on:
    push:
      branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: 11
            distribution: 'temurin'
            cache: maven
        - name: install with Maven
          run: mvn clean install

        - name: Create a Dockerfile
          run: |
            echo "
             FROM maven AS build
             COPY src /app/src
             COPY pom.xml /app
             RUN mvn -f /app/pom.xml clean package

             FROM openjdk:11
             COPY --from=build /app/target/springmaven-0.0.1-SNAPSHOT.jar ./build.jar
             ENTRYPOINT ["java","-jar","./build.jar"]
             " > Dockerfile

        - name: Docker login
          uses: docker/login-action@v1 
          with:
            registry: registry.patr.cloud
            username: ashish-oli
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Build image from Dockerfile and push to patr-registry
          run: |
            docker build . -t ashish-oli/deployment
            docker tag ashish-oli/deployment registry.patr.cloud/personal-workspace-e883956e0ede454a8c06e7afe768de5f/maven:latest 
            docker push registry.patr.cloud/personal-workspace-e883956e0ede454a8c06e7afe768de5f/maven:latest 
